<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <UnityEditorRoot Condition="'$(UnityEditorRoot)' == ''">C:/Program Files/Unity/Hub/Editor/2022.3.62f3c1/Editor</UnityEditorRoot>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Assets/Scripts/**/*.cs" />
    <Compile Include="../Assets/Editor/**/*.cs" />
    <Reference Include="$(UnityEditorRoot)/Data/Managed/UnityEngine/*.dll" />
    <Reference Include="$(UnityEditorRoot)/Data/Managed/UnityEditor/*.dll" />
    <Reference Include="../Library/ScriptAssemblies/UnityEngine.UI.dll" />
  </ItemGroup>
</Project>
